DRA: Integrates with DRA and CDI (#3329)
* DRA: new api defination

Signed-off-by: cyclinder <qifeng.guo@daocloud.io>

* feature: Integrates with DRA and CDI

Signed-off-by: cyclinder <qifeng.guo@daocloud.io>

Now spiderpool integrates dra and cdi, which allows for some complex scheduling and better manipulation of hardware resources based on dra.

* DRA: Avoids cdi's device have empty containerEdits

Signed-off-by: cyclinder <qifeng.guo@daocloud.io>

* DRA: Fix issues in charts

* DRA: Fix error chmod the CDI file

Signed-off-by: cyclinder <qifeng.guo@daocloud.io>

* DRA: Implement UnPrepareResource interface for NodeServer

Signed-off-by: cyclinder <qifeng.guo@daocloud.io>

* DRA: Fix code format

Signed-off-by: cyclinder <qifeng.guo@daocloud.io>

* DRA: Fix the comments of the review

Signed-off-by: cyclinder <qifeng.guo@daocloud.io>

* DRA: add e2e tests

Signed-off-by: cyclinder <qifeng.guo@daocloud.io>

* DRA: Fix the feedback

* DRA: add docs of quick-start

* DRA: Fix the latest feedback

* DRA: Fix the latest feedback

---------

Signed-off-by: cyclinder <qifeng.guo@daocloud.io>

diff --git a/test/Makefile b/test/Makefile
--- a/test/Makefile
+++ b/test/Makefile
@@ -153,16 +153,20 @@ setup_kind:
 			sed -i  ''"$${INSERT_LINE}"' a \  podSubnet: "$(CLUSTER_POD_SUBNET_V4),$(CLUSTER_POD_SUBNET_V6)"' $${NEW_KIND_YAML}  ; \
 			sed -i  ''"$${INSERT_LINE}"' a \  serviceSubnet: "$(K8S_IPV4_SERVICE_CIDR),$(K8S_IPV6_SERVICE_CIDR)"' $${NEW_KIND_YAML}  ; \
   		fi ; \
-		MultiCIDRServiceGateVersion="v1.29.0" ; \
-		if [ $$(echo -e "$(E2E_KIND_IMAGE_TAG)\n$${MultiCIDRServiceGateVersion}" | sort -V | tail -n1) == "$(E2E_KIND_IMAGE_TAG)" ]; then \
-			echo "the following features are only fully supported in versions higher than $${MultiCIDRServiceGateVersion}." ; \
-			sed -i  '$$  a\featureGates: ' $${NEW_KIND_YAML}  ; \
-			sed -i  '$$  a\   MultiCIDRServiceAllocator: true' $${NEW_KIND_YAML}  ; \
+		if [ $$(echo -e "$(E2E_KIND_IMAGE_TAG)\nv1.29.0" | sort -V | tail -n1) == "$(E2E_KIND_IMAGE_TAG)" ]; then \
+			echo "the following features are only fully supported in versions higher than v1.29.0." ; \
 			sed -i  '$$  a\runtimeConfig: ' $${NEW_KIND_YAML}  ; \
 			sed -i  '$$  a\   api/alpha: "true"' $${NEW_KIND_YAML}  ; \
-		fi
-	$(QUIET) cat $(CLUSTER_DIR)/$(E2E_CLUSTER_NAME)/kind-config.yaml
-	KIND_OPTION="" ; \
+			sed -i  '$$  a\featureGates: ' $${NEW_KIND_YAML}  ; \
+			sed -i  '$$  a\   MultiCIDRServiceAllocator: true' $${NEW_KIND_YAML}  ; \
+			if [ "${E2E_SPIDERPOOL_ENABLE_DRA}" == "true" ]; then \
+				sed -i  '$$  a\   DynamicResourceAllocation: true' $${NEW_KIND_YAML}  ; \
+				printf 'containerdConfigPatches: \n# Enable CDI as described in https://tags.cncf.io/container-device-interface#containerd-configuration\n- |-\n  [plugins."io.containerd.grpc.v1.cri"]\n    enable_cdi = true\n ' >> $${NEW_KIND_YAML} ; \
+			fi ;\
+		fi ; \
+	$(QUIET) cat $(CLUSTER_DIR)/$(E2E_CLUSTER_NAME)/kind-config.yaml ; \
+	echo "-------------" ; \
+		KIND_OPTION="" ; \
        		[ -n "$(E2E_KIND_IMAGE_TAG)" ] && KIND_OPTION=" --image $(E2E_KIND_IMAGE_NAME):$(E2E_KIND_IMAGE_TAG) " && echo "setup kind with $(E2E_KIND_IMAGE_NAME):$(E2E_KIND_IMAGE_TAG)"; \
             kind create cluster --config $(CLUSTER_DIR)/$(E2E_CLUSTER_NAME)/kind-config.yaml \
 			--name $(E2E_CLUSTER_NAME) --kubeconfig $(E2E_KUBECONFIG) $${KIND_OPTION}
@@ -173,7 +177,14 @@ setup_kind:
 		kubectl get node --kubeconfig $(E2E_KUBECONFIG) &>/dev/null && break ; \
 		echo "wait for node ready" ; \
 	done ; \
-    kubectl get node --kubeconfig $(E2E_KUBECONFIG) &>/dev/null || { echo "error, cluster is not ready" ; exit 1 ; }
+	kubectl get node --kubeconfig $(E2E_KUBECONFIG) &>/dev/null || { echo "error, cluster is not ready" ; exit 1 ; }
+	if [ "$(E2E_SPIDERPOOL_ENABLE_DRA)" == "true" ] ; then \
+		NODE_LIST=` docker ps | egrep "kindest/node.* $(E2E_CLUSTER_NAME)-(control|worker)" | awk '{print $$1 }' ` ; \
+		[ -n "$$NODE_LIST" ] || { echo "error, failed to find any kind nodes, please setup kind cluster $(E2E_CLUSTER_NAME) first" ; exit 1 ; } ; \
+		for NODE in $${NODE_LIST} ; do \
+			docker exec $${NODE} touch $(E2E_SPIDERPOOL_DRA_SOLIBRARY_PATH) ; \
+		done \
+	fi ; \
 	echo "show kubernetes node image " && docker ps
 	@echo "===================== deploy prometheus CRD ========== "
 	{ timeout 10 kubectl apply --kubeconfig $(E2E_KUBECONFIG) -f https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/main/example/prometheus-operator-crd/monitoring.coreos.com_servicemonitors.yaml ; } \
@@ -225,13 +236,18 @@ setup_spiderpool:
 		else \
 		  	HELM_OPTION+=" --set coordinator.enabled=false " ; \
 		fi ; \
+		# dra is only enable in v1.28.0
+		if [ $$(echo -e "$(E2E_KIND_IMAGE_TAG)\nv1.29.0" | sort -V | tail -n1) == "$(E2E_KIND_IMAGE_TAG)" ] && [ "${E2E_SPIDERPOOL_ENABLE_DRA}" == "true" ]; then \
+			HELM_OPTION+=" --set dra.enabled=true " ; \
+			HELM_OPTION+=" --set dra.hostDevicePath=$(E2E_SPIDERPOOL_DRA_SOLIBRARY_PATH) " ; \
+		fi ; \
 		HELM_OPTION+=" --set multus.multusCNI.install=true " ; \
 		HELM_OPTION+=" --set multus.multusCNI.image.registry= " ; \
 		HELM_OPTION+=" --set multus.multusCNI.image.repository=$(E2E_MULTUS_IMAGE_NAME) " ; \
 		if [ "$(INSTALL_OVERLAY_CNI)" == "true" ]; then \
-		HELM_OPTION+=" --set multus.multusCNI.defaultCniCRName= " ; \
+			HELM_OPTION+=" --set multus.multusCNI.defaultCniCRName= " ; \
 		else \
-		HELM_OPTION+=" --set multus.multusCNI.defaultCniCRName=$(MULTUS_DEFAULT_CNI_VLAN0) " ; \
+			HELM_OPTION+=" --set multus.multusCNI.defaultCniCRName=$(MULTUS_DEFAULT_CNI_VLAN0) " ; \
 		fi ; \
 		if [ "$(E2E_SPIDERPOOL_ENABLE_MULTUSCONFIG)" == "true" ] ; then \
 			HELM_OPTION+=" --set multus.enableMultusConfig=true " ; \
@@ -464,6 +480,13 @@ e2e_test:
 		export RELEASE_NAMESPACE=$(RELEASE_NAMESPACE) ; \
 		export INSTALL_OVERLAY_CNI=$(INSTALL_OVERLAY_CNI) ; \
 		export E2E_SPIDERSUBNET_ENABLED=$(E2E_SPIDERPOOL_ENABLE_SUBNET) ; \
+		K8S_VERSION=` kubectl version -o json --kubeconfig $(E2E_KUBECONFIG) | jq '.serverVersion.gitVersion' ` ; \
+		echo "k8s version: $${K8S_VERSION}" ; \
+		if [ $$(echo -e "$(K8S_VERSION)\nv1.29.0" | sort -V | tail -n1) == "$(K8S_VERSION)" ] && [ "${E2E_SPIDERPOOL_ENABLE_DRA}" == "true" ]; then \
+			export E2E_SPIDERPOOL_ENABLE_DRA=true ; \
+		else \
+			export E2E_SPIDERPOOL_ENABLE_DRA=false ; \
+		fi ; \
 		rm -f $(E2E_LOG_FILE) || true  ; \
 		echo "=========== before test `date` ===========" >> $(E2E_LOG_FILE) ; \
 		./scripts/debugEnv.sh $(E2E_KUBECONFIG) "system" "$(E2E_LOG_FILE)" ; \
