ci: add some debug log
Signed-off-by: weizhou.lan@daocloud.io <weizhou.lan@daocloud.io>

diff --git a/test/Makefile b/test/Makefile
--- a/test/Makefile
+++ b/test/Makefile
@@ -249,8 +249,8 @@ e2e_test:
 		echo "=========== after test `date` ===========" >> $(E2E_LOG_FILE) ; \
 		./scripts/debugEnv.sh $(E2E_KUBECONFIG) "gops" "$(E2E_LOG_FILE)" ; \
 		./scripts/debugEnv.sh $(E2E_KUBECONFIG) "detail" "$(E2E_LOG_FILE)" ; \
-		./scripts/debugEnv.sh $(E2E_KUBECONFIG) "longlock" "$(E2E_LOG_FILE)" || RESULT=1 ; \
-		./scripts/debugEnv.sh $(E2E_KUBECONFIG) "datarace" "$(E2E_LOG_FILE)" || RESULT=1 ; \
+		./scripts/debugEnv.sh $(E2E_KUBECONFIG) "longlock" "$(E2E_LOG_FILE)" || { echo "error, found long lock !!!" ; RESULT=1 ; } ; \
+		./scripts/debugEnv.sh $(E2E_KUBECONFIG) "datarace" "$(E2E_LOG_FILE)" || { echo "error, found data race !!!" ; RESULT=1 ; } ; \
 		if (($${RESULT} != 0)) ; then \
 		   echo "failed to run e2e test"  ; \
 		   exit 1 ; \
