gc ci image

diff --git a/.github/workflows/ci-image-gc-interval.yaml b/.github/workflows/ci-image-gc-interval.yaml
--- a/.github/workflows/ci-image-gc-interval.yaml
+++ b/.github/workflows/ci-image-gc-interval.yaml
@@ -9,6 +9,21 @@ on:
   schedule:
     # Run the GC at 3am each day
     - cron: "0 3 * * *"
+  workflow_dispatch:
+    inputs:
+      dry_run:
+        description: 'dry run, (bool)'
+        required: true
+        default: true
+      age_day:
+        description: 'the day that image have exist will be pruned (0 for all) '
+        required: true
+        default: "1"
+      tag_reg:
+        description: 'tag regular expression for pruned image'
+        required: true
+        default: ".*"
+
 
 jobs:
   purge-image:
@@ -21,16 +36,49 @@ jobs:
           - name: spiderpool-controller
 
     steps:
+      - name: Check Dispatch Value
+        if: ${{ github.event_name == 'workflow_dispatch' }}
+        continue-on-error: false
+        id: value
+        run: |
+          v=${{ github.event.inputs.dry_run }}
+          if [ "$v" != "true" ] && [ "$v" != "false" ] ; then
+              echo "error, dry_run must be true or false"
+              exit 1
+          fi
+
       - name: Delete CI image
         uses: vlaurin/action-ghcr-prune@v0.4.0
+        if: ${{ github.event_name == 'workflow_dispatch' }}
         with:
           token: ${{ secrets.GHCR_PASSWARD }}
           organization: ${{ github.repository_owner }}
           container: ${{ env.ONLINE_REGISTER }}/${{ github.repository }}/${{ matrix.name }}-ci
-          dry-run: false # Dry-run first, then change to `false`
+          # Dry-run first, then change to `false`
+          dry-run: ${{ github.event.inputs.dry_run }}
           # Minimum age in days of a version before it is pruned. Defaults to 0 which matches all versions of a container
           # longer than 1 days, will gc it
-          older-than: 1 # days
+          older-than: ${{ github.event.inputs.age_day }}
+          # Count of most recent, matching containers to exclude from pruning
+          keep-last: 0
+          #untagged versions should be pruned
+          untagged: true
+          # if no tag-regex , all tag will be pruned
+          tag-regex: "${{ github.event.inputs.tag_reg }}"
+
+
+      - name: Delete CI image
+        uses: vlaurin/action-ghcr-prune@v0.4.0
+        if: ${{ github.event_name != 'workflow_dispatch' }}
+        with:
+          token: ${{ secrets.GHCR_PASSWARD }}
+          organization: ${{ github.repository_owner }}
+          container: ${{ env.ONLINE_REGISTER }}/${{ github.repository }}/${{ matrix.name }}-ci
+          # Dry-run first, then change to `false`
+          dry-run: false
+          # Minimum age in days of a version before it is pruned. Defaults to 0 which matches all versions of a container
+          # longer than 1 days, will gc it
+          older-than: 1
           # Count of most recent, matching containers to exclude from pruning
           keep-last: 0
           #untagged versions should be pruned
